import { Cache } from "../models/Cache";

export const DUMMY_CACHES: Cache[] = [
  {
    code: "GC00001",
    name: "Skogsmysteriet",
    description:
      "En gömma djupt inne i skogen där fågelsång och gamla stigar leder vägen.",
    lat: 59.1282,
    lng: 15.152,
    type: "Traditionell",
    difficulty: 2,
    terrain: 3,
    found: true,
  },
  {
    code: "GC00002",
    name: "Hamnen",
    description:
      "Vid den gamla hamnen gömmer sig en cache med utsikt över vattnet.",
    lat: 59.1245,
    lng: 15.158,
    type: "Multi",
    difficulty: 3,
    terrain: 2,
    found: false,
  },
  {
    code: "GC00003",
    name: "Gamla kyrkan",
    description:
      "En historisk plats där cachen gömts nära den gamla stenmuren.",
    lat: 59.131,
    lng: 15.145,
    type: "Traditionell",
    difficulty: 1,
    terrain: 1,
    found: true,
  },
  {
    code: "GC00004",
    name: "Utsiktsplatsen",
    description:
      "Ta dig upp till höjden och njut av utsikten innan du letar vidare.",
    lat: 59.135,
    lng: 15.149,
    type: "Mystery",
    difficulty: 4,
    terrain: 4,
    found: false,
  },
  {
    code: "GC00005",
    name: "Tallstigen",
    description: "En enkel promenad genom tallskogen leder till denna gömma.",
    lat: 59.1271,
    lng: 15.1604,
    type: "Event",
    difficulty: 2,
    terrain: 2,
    found: false,
  },
  {
    code: "GC00006",
    name: "Bron över ån",
    description: "Under bron hörs vattnet porla medan du söker efter cachen.",
    lat: 59.1229,
    lng: 15.1508,
    type: "Wherigo",
    difficulty: 1,
    terrain: 1,
    found: false,
  },
  {
    code: "GC00007",
    name: "Björkarnas hemlighet",
    description: "Björkarna viskar om en gömma som få lyckats hitta snabbt.",
    lat: 59.1336,
    lng: 15.1419,
    type: "Mystery",
    difficulty: 4,
    terrain: 3,
    found: false,
  },
  {
    code: "GC00008",
    name: "Fiskebryggan",
    description:
      "En cache placerad nära bryggan där fiskare samlas tidiga morgnar.",
    lat: 59.1257,
    lng: 15.1633,
    type: "Multi",
    difficulty: 3,
    terrain: 2,
    found: false,
  },
  {
    code: "GC00009",
    name: "Stenröset",
    description: "Mellan mossiga stenar och gamla rösen väntar nästa fynd.",
    lat: 59.1364,
    lng: 15.1541,
    type: "Traditionell",
    difficulty: 2,
    terrain: 4,
    found: false,
  },
  {
    code: "GC00010",
    name: "Skogsgläntan",
    description:
      "En lugn glänta mitt i skogen där solen når marken mellan träden.",
    lat: 59.1294,
    lng: 15.1468,
    type: "Traditionell",
    difficulty: 1,
    terrain: 2,
    found: false,
  },
  {
    code: "GC00011",
    name: "Vandrarnas vila",
    description:
      "Perfekt plats för en paus innan nästa del av vandringen börjar.",
    lat: 59.1215,
    lng: 15.1567,
    type: "Traditionell",
    difficulty: 2,
    terrain: 2,
    found: false,
  },
  {
    code: "GC00012",
    name: "Gamla eken",
    description: "En mäktig ek markerar platsen för denna EarthCache.",
    lat: 59.1378,
    lng: 15.1472,
    type: "EarthCache",
    difficulty: 3,
    terrain: 1,
    found: false,
  },
  {
    code: "GC00013",
    name: "Mossiga stenen",
    description: "Den gröna mossan gör stenen lätt att känna igen i området.",
    lat: 59.1263,
    lng: 15.1398,
    type: "Traditionell",
    difficulty: 1,
    terrain: 3,
    found: false,
  },
  {
    code: "GC00014",
    name: "Nattugglans gömma",
    description:
      "Den här mystiska cachen är bäst att leta efter när mörkret faller.",
    lat: 59.1325,
    lng: 15.1611,
    type: "Mystery",
    difficulty: 5,
    terrain: 2,
    found: false,
  },
  {
    code: "GC00015",
    name: "Vindskyddet",
    description:
      "Ett gammalt vindskydd ger skydd åt både vandrare och cacheletare.",
    lat: 59.1188,
    lng: 15.1486,
    type: "Traditionell",
    difficulty: 2,
    terrain: 2,
    found: true,
  },
  {
    code: "GC00016",
    name: "Röda ladan",
    description: "Den röda ladan syns på långt håll och leder dig rätt.",
    lat: 59.1234,
    lng: 15.1425,
    type: "Multi",
    difficulty: 3,
    terrain: 3,
    found: false,
  },
  {
    code: "GC00017",
    name: "Kvarnruinen",
    description:
      "Gamla ruiner och porlande vatten omger denna klassiska cacheplats.",
    lat: 59.1342,
    lng: 15.165,
    type: "Traditionell",
    difficulty: 2,
    terrain: 4,
    found: false,
  },
  {
    code: "GC00018",
    name: "Hemliga passagen",
    description:
      "En dold passage leder till en av områdets mest spännande cacher.",
    lat: 59.1307,
    lng: 15.1576,
    type: "Mystery",
    difficulty: 4,
    terrain: 2,
    found: true,
  },
  {
    code: "GC00019",
    name: "Lilla sjöutsikten",
    description:
      "Här får du både sjöutsikt och en relativt enkel cache att hitta.",
    lat: 59.1199,
    lng: 15.1533,
    type: "Traditionell",
    difficulty: 1,
    terrain: 1,
    found: false,
  },
  {
    code: "GC00020",
    name: "Granarnas cirkel",
    description:
      "Granarna står tätt runt platsen och skapar nästan en naturlig ring.",
    lat: 59.1385,
    lng: 15.1437,
    type: "Traditionell",
    difficulty: 3,
    terrain: 3,
    found: false,
  },
];
